"use client";

import { useLocale } from "./LocaleProvider";
import type { Locale } from "@/lib/i18n/config";

const OPTIONS: Locale[] = ["pt", "en"];

/** Interface language switch — only affects the product texts, never the post generated by the AI. */
export function LanguageSwitcher({ className = "" }: { className?: string }) {
  const { locale, dict, setLocale } = useLocale();

  return (
    <div
      role="group"
      aria-label={dict.common.language.label}
      className={`inline-flex rounded-full border border-line bg-elevated p-0.5 text-xs font-medium ${className}`}
    >
      {OPTIONS.map((option) => (
        <button
          key={option}
          type="button"
          onClick={() => setLocale(option)}
          aria-pressed={locale === option}
          className={`rounded-full px-2.5 py-1.5 transition-colors sm:px-3 ${
            locale === option ? "bg-brand-500 text-black" : "text-muted hover:text-ink"
          }`}
        >
          {/* Short code on phones, full name from sm up — keeps the header from overflowing. */}
          <span className="sm:hidden">{option.toUpperCase()}</span>
          <span className="hidden sm:inline">{dict.common.language[option]}</span>
        </button>
      ))}
    </div>
  );
}
